allprojects {
    repositories {
        google()
        mavenCentral()
    }
    tasks.withType(Javadoc) {
        // Disable lint, due to issues in the EventBus code comments.
        options.addStringOption('Xdoclint:none', '-quiet')
        options.addStringOption('encoding', 'UTF-8')
    }
}

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.8.0'
    }
}

ext {
    compileSdkVersion = 35
    minSdkVersion = 21
    targetSdkVersion = 34

    assert minSdkVersion <= targetSdkVersion : "minSdkVersion too big"
    assert targetSdkVersion <= compileSdkVersion : "targetSdkVersion too big"
}
